# Site settings
title: "Simulacrum"
author: "Jonathan Crum"
description: "A blog and personal notebook."
keywords: "Linguistics, Mathematics, Philosophy, Programming"
biography: "I am a PhD student at the University of Georgia."
colophon: "© 2019-2020 by Jonathan Crum."

baseurl: ""
url: "http://simulacrum.space"

github_username: krummja

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

mathjax: true
mathjax_autoNumber: true
chart: true
